### GET home
GET http://localhost:5008/

### GET steden
GET http://localhost:5008/steden

### GET weerstations
GET http://localhost:5008/weerstations

### GET metingen
GET http://localhost:5008/metingen

### GET weerbericht
GET http://localhost:5008/weerbericht

### POST doemetingen
POST http://localhost:5008/doemetingen